### ISSUE TITLE
Can you help me I've been going literally crazy for two days...reading netcdf WOA23 file from NOAA.

### ISSUE THREAD

**Issue by Vytek** [batchatco/go-native-netcdf#14]
I am making a free and open source submarine simulation environment and I have the task of reading this netcdf file that reports the salinity given a certain latitude, longitude and depth. I think I guessed that since it is not a 1-dimensional variable it must use something very similar to the code (https://github.com/batchatco/go-native-netcdf/issues/2). **Please help me I absolutely can't figure out how to load the variable _s_an_ having latitude, longitude and depth. If I succeed I promise to upload a complete example that uses this beautiful native library on golang among the examples. Thanks, thanks and I hope for your help!**

File to read is: 
https://www.ncei.noaa.gov/data/oceans/woa/WOA23/DATA/salinity/netcdf/decav/1.00/woa23_decav_s01_01.nc
From:
https://www.ncei.noaa.gov/access/world-ocean-atlas-2023/bin/woa23.pl

Using ncdump this is the main variables:

ncdump -c woa23_decav_s01_01.nc | less
variables:
        int crs ;
                crs:grid_mapping_name = "latitude_longitude" ;
                crs:epsg_code = "EPSG:4326" ;
                crs:longitude_of_prime_meridian = 0.f ;
                crs:semi_major_axis = 6378137.f ;
                crs:inverse_flattening = 298.2572f ;
        float lat(lat) ;
                lat:standard_name = "latitude" ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
                lat:bounds = "lat_bnds" ;
        float lat_bnds(lat, nbounds) ;
                lat_bnds:comment = "latitude bounds" ;
        float lon(lon) ;
                lon:standard_name = "longitude" ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
                lon:bounds = "lon_bnds" ;
        float lon_bnds(lon, nbounds) ;
                lon_bnds:comment = "longitude bounds" ;
        float depth(depth) ;
                depth:standard_name = "depth" ;
                depth:bounds = "depth_bnds" ;
                depth:positive = "down" ;
                depth:units = "meters" ;
                depth:axis = "Z" ;
        float depth_bnds(depth, nbounds) ;
                depth_bnds:comment = "depth bounds" ;
        float time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:units = "months since 1955-01-01 00:00:00" ;
                time:axis = "T" ;
                time:climatology = "climatology_bounds" ;
        float climatology_bounds(time, nbounds) ;
                climatology_bounds:comment = "This variable defines the bounds of the climatological time period for each time" ;
        float s_an(time, depth, lat, lon) ;
                s_an:standard_name = "sea_water_practical_salinity" ;
                s_an:long_name = "Objectively analyzed mean fields for sea_water_practical_salinity at standard depth levels." ;
                s_an:coordinates = "time lat lon depth" ;
                s_an:cell_methods = "area: mean depth: mean time: mean within years time: mean over years" ;
                s_an:grid_mapping = "crs" ;
                s_an:units = "1" ;
                s_an:_FillValue = 9.96921e+36f ;

**Comment by batchatco** [comment]
I don't see a variable named `s_an`, but I see one named `t_an` in `woa23_decav_s01_01.nc`.

```c
    float t_an(time, depth, lat, lon) ;
```

I am able to read it, as follows:

```go

package main

import (
  "fmt"
  "log"

  "github.com/batchatco/go-native-netcdf/netcdf"
)

const (
  inputFile = "woa23_decav_t01_01.nc"
  variable  = "t_an"
)

func main() {
  ncf, err := netcdf.Open(inputFile)
  if err != nil {
    log.Fatalf("Error opening %q: %v", inputFile, err)
  }

  nc, err := ncf.GetGroup("/")
  if err != nil {
    log.Fatalf("Error opening group: %v", err)
  }
  vr, err := nc.GetVariable(variable)
  if err	!= nil {
    log.Fatalf("Error reading %q: %v", variable, err)
  }
  t_an := vr.Values.([][][][]float32)
  fmt.Printf("%5s %5s %5s %5s %s\n", "time", "depth", "lat", "lon", "value")
  for time, depthv := range t_an {
    for depth, latv := range depthv {
      for lat, lonv := range latv {
        for lon, value := range lonv {
          fmt.Printf("%5v %5v %5v %5v %v\n", time, depth, lat, lon, value)
        }
      }
    }
  }
}
```

**Comment by Vytek** [comment]
Than you very much! My mistake, there Is a similar file with temperature but the Logic Is the same! Thanks again!
