### ISSUE TITLE
Get wrong value when variable with compression

### ISSUE THREAD

**Issue by sawyerzhu** [batchatco/go-native-netcdf#4]
Thanks for this usable library.

I meet a problem when reading variable value If a variable value with compression. I will get wrong value.

I do some debug, found hdf5.go file newRecordReader function those lines maybe has bug

```
if int64(thisSeg.offset+thisSeg.length) > h5.fileSize {
	if int64(thisSeg.offset) >= h5.fileSize {
		thisSeg.r = makeFillValueReader(obj, nil, int64(thisSeg.length))
	} else {
		length := h5.fileSize - int64(thisSeg.offset)
		rr := newResetReader(thisSeg.r, length)
		thisSeg.r = makeFillValueReader(obj, rr, int64(thisSeg.length))
	}
}
```

this line `length := h5.fileSize - int64(thisSeg.offset)' will get wrong length for compression variable values. I change `rr := newResetReader(thisSeg.r, length)` to `rr := newResetReader(thisSeg.r, int64(thisSeg.length))` seem get right values.

I am not sure this change is right, please help.

**Comment by batchatco** [comment]
Fixed with 9ac0218931d0a0b5f28a98b8a6802a987a924be4.

Thanks for verifying it!
