### ISSUE TITLE
whether support load single chunk data?

### ISSUE THREAD

**Issue by absolutelyZero** [batchatco/go-native-netcdf#9]
Now ,I have a hdf5 file which have 284 chunk in one dataset. I just want to load one chunk data at once for speed,no all dataset data.

So, I want to know whether support load single chunk data. I look forward to your reply. If not suppot, is there a plan to support it in the future?

Thanks.

**Comment by batchatco** [comment]
You can use GetSlice  for this.

	// GetSlice gets a (smaller) slice of the variable's slice
	// It's useful for variables which are very large and may not fit in memory.
	GetSlice(begin, end int64) (interface{}, error)
